### ISSUE TITLE
illegal hardware instruction

### ISSUE THREAD

**Issue by hr4dw4y** [ThoughtfulDev/EagleEye#20] opened 2018-07-05 19:32 UTC
Just to confirm, when I tried to run the software, returned the following error.

> python3 eagle-eye.py
 [1]    2090 illegal hardware instruction  python3 eagle-eye.py 
running on vmware 12

it means that my hardware does not support this software

> cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Pentium(R) Dual-Core  CPU      E5700  @ 3.00GHz
stepping	: 10
microcode	: 0xa07
cpu MHz		: 2992.415
cache size	: 2048 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf pni ssse3 cx16 x2apic tsc_deadline_timer xsave hypervisor lahf_lm pti tsc_adjust dtherm
bugs		: cpu_meltdown spectre_v1 spectre_v2
bogomips	: 5984.83
clflush size	: 64
cache_alignment	: 64
address sizes	: 42 bits physical, 48 bits virtual
power management:

**Comment by ThoughtfulDev** [comment] 2018-07-05 20:08
This problem seems to be caused by a set of instructions that are not hardware implemented in some older processors (AVX instruction set). Since they are not implemented in hardware, there's no real fix for this problem.

If I understood it correctly, and a workaround is to downgrade tensorflow from 1.6.0 to 1.5.0, this also applies to the GPU version.

So uninstall tensorflow and install tensorflow==1.5.0

Alternatively try to enable AVX instructions in VMware (if your CPU supports it)

**Comment by ThoughtfulDev** [comment] 2018-07-09 18:46
@hr4dw4y  Did that fix your Issue?

**Closed** 2018-07-13 13:23 UTC
