### ISSUE TITLE
Extending the number of facebook public pictures  to be checked in face-recognition

### ISSUE THREAD

**Issue by Tudorvr** [ThoughtfulDev/EagleEye#11] opened 2018-05-17 12:54 UTC
I was wondering if it would be possible to extend the number of public pictures to be downloaded from each facebook profile and then to be compared in the face-recognition check phase. Thus I believe the chances for a correct match would be highly increased. Of course, we can set a small number of pictures to be downloaded ( for e.g. all profiles pics or all mobile album pics )

**Comment by ThoughtfulDev** [comment] 2018-05-20 09:20
The Problem is that one needs to be logged in to be able to the Photos of Persons (even if they are public). Correct me if i'm wrong.
Since the whole purpose is to not need an account i dont think that this will be possible.

**Comment by Tudorvr** [comment] 2018-05-20 15:31
You`re right, a login phase would be required. This way correct recognition percent would be highly increased.

**Comment by ThoughtfulDev** [comment] 2018-05-28 08:08
You are welcome to make a pull request which adds this feature. Maybe via a `--login creds.txt` flag which reads the credentials from a textfile.
Since i this tool should not need a FB Account, i'm not sure if i would add this feature.

**Comment by ThoughtfulDev** [comment] 2018-05-31 17:27
Closing this for now. (Pull Requests welcome)

**Closed by ThoughtfulDev** 2018-05-31 17:27 UTC
Labels: enhancement
