### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by evilcoder13** [ThoughtfulDev/EagleEye#32] opened 2018-07-24 09:13 UTC
![image](https://user-images.githubusercontent.com/19726972/43128549-756af162-8f5c-11e8-9064-b9d17ae3440c.png)
After installed automatically and added required python package using pip, got this error when running as per instructed.

**Comment by ThoughtfulDev** [comment] 2018-07-24 10:13
Duplicate of #26 

Check Issue #18
Tl;dr: try Python 3.6

**Closed by ThoughtfulDev** 2018-07-24 10:13 UTC
