### ISSUE TITLE
Error after inserting jitter

### ISSUE THREAD

**Issue by Alefunshow** [ThoughtfulDev/EagleEye#59] opened 2019-03-20 23:40 UTC
![Errore facerecog](https://user-images.githubusercontent.com/38226690/54726091-cc26e700-4b71-11e9-90b1-56c1c8f4320a.PNG)

**Comment by ThoughtfulDev** [comment] 2019-03-21 16:53
Duplicate of #57 . Please use that issue.

**Closed by ThoughtfulDev** 2019-03-21 16:53 UTC
